### ISSUE TITLE
Feature proposal: sync time short time before bidding

### ISSUE THREAD

**Issue by mmoole** [sweitzel/Biet-O-Matic-BE#19]
Today it happened that the bidding process started exactly at the end time of the item at eBay.
So the bidding was not successful:
![Bildschirmfoto_2020-10-25_um_22_47_09](https://user-images.githubusercontent.com/678765/97120098-21938480-1715-11eb-9e1c-6ed50df24747.png)
As it seems in the log, between the time of opening the browser tab and bidding, it would make sense to 'sync the clock' with the time at ebay - maybe 2 times to be reliable, and set the bidding time accordingly.
The time in the settings of the extension is 5 seconds (default). 
Maybe this was due to daylight saving time ending today?

**Comment by sweitzel** [comment]
BE already synchronizes the time roughly every hour by default. Could you check on https://time.is/ if your computer time is maybe already exact?

**Comment by mmoole** [comment]
The laptop was in standby mode in between - the time is accurate to 4 to 5 ms as displayed by time.is and uhr.ptb.de.
Maybe it was a bit off set when this happened. 
Nevertheless looking at the log would mean that BE synced to a specific time that was about 5 seconds off relative to the system time of the computer - otherwise I couldn't explain the time it chose for bidding...!? Or maybe do I misunderstand the process?
Is there more logging I could extract for this?

**Comment by sweitzel** [comment]
The Bidding process is described in the [integrated BE documentation](chrome-extension://jncdemkhnhalpbopijhbmigeopglapli/doc/en/manual/features.html#bidding-procedure). From the bidding log visible in your screenshot its pretty obvious that the procedure was initiated early enough, but simply the bidding took not place at the right time. 

If you use the default of bidding 5s before the auction ends, the bid was executed at least 5s too late. You can compare with the screenshot of one of my auctions and see that the "Phase 3" starts 5s earlier than in your example, and bidding takes place at the right time 4.5s before the auction ended.

I am pretty sure now this is related to the `setTimeout` not working reliably. This is likely related to a [change in Chrome 86](https://www.ghacks.net/2020/10/07/google-chrome-86-is-out-with-password-changing-improvements-and-security-patches/) ([or here](https://docs.google.com/document/d/1sd9EVERCtRWKvnJXnP3iZ83fM3FLwDbjiyfMkaKWEYk/edit) more technical) which is intended to improve Battery-saving.

I will threat this as a bug and instead of sleeping once until the bidding time, will change to sleeping at shorter intervals.

Until then, as a workaround please adjust your bidding time to 10s, better 15s which should be reliable enough to avoid the issue.

![image](https://user-images.githubusercontent.com/1214038/97257386-0bb9b880-1816-11eb-837b-bdb7e1f02556.png)

**Comment by mmoole** [comment]
Yes, I then increased the time before bidding to 10 seconds as a first measure. 
I forgot to mention: this is running in Firefox (I think it was version 81, I made the update to 82 just yesterday), and the Laptop is getting power from the power supply, on MacOS X 10.15.7.
(Some days before it worked flawlessly, just as a note.)

**Comment by mikhoul** [comment]
Does this issue is resolved or I must add more time ?  

If  we keep a window (not a tab) open with BOM  the JS-timer should not be throttled.

Note: A maybe possible fix/workaround when a BOM tabs/window is open would be to simulate some minor actions (like "phantom" mouse clicking in an empty area of the tab/window) every 30 minutes this way it would keep the tab/windows timer awake.

I have another extension that is scheduled to to crawl the web and look for some change in the background and the  the way it work is it open a "dummy window" when I start my browser so this way the program always run in it's own Windows. 

I've dogged more on the subject and I have found a better fix that should stay for some time in Chromium: There is a flag to prevent JS-Timer from being throttled, you have multiple choices look at the screenshot:

`chrome://flags/#intensive-wake-up-throttling`

![image](https://user-images.githubusercontent.com/5678673/100671616-c9acf680-332e-11eb-8e35-2defbf550a06.png)


But the most realistic and effective way IMO would be that when BOM is loaded at the browser start BOM should open a dummy window of it's own to keep the JStimer from being throttled. 

 Look at the dummy windows from another extension that need to run in background:


![image](https://user-images.githubusercontent.com/5678673/100672105-712a2900-332f-11eb-9470-0e0c5f568f71.png)




Regards :octocat:

**Comment by sweitzel** [comment]
I have added better logging for timing related bidding issues with version 0.5.3. Also the bid time has been changed from default 5s to 10s. 

Before making more changes, I am eager to see how this behaves now. This is quite hard to reproduce, so please provide logs in case you observe this issue.
